### ISSUE TITLE
New entry to the Planetarium list, is a RSS feed needed?

### ISSUE THREAD

**Issue by mendaomn** [stoyan/perfplanet#60]
I've been writing a [web performance blog](https://westwingsolutions.com/pages/blog) for a couple of months now and I would be honored to be listed among the giants ;) 

However, I haven't configured a RSS feed (yet, not sure on how to go about it), is it necessary? 

Thanks and awesome work everybody, keep up!

**Comment by stoyan** [comment]
looks cool, but yeah, I need an rss feed
